"""empty message

Revision ID: 9f1eff9d19b8
Revises: ae7a3f8c9702
Create Date: 2023-07-31 12:25:44.576732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1eff9d19b8'
down_revision = 'ae7a3f8c9702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary2', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('salary2')

    # ### end Alembic commands ###
